### ISSUE TITLE
Go Phish Server is trivially fingerprintable

### ISSUE THREAD

**Issue by ncc-nathanhays** [fin3ss3g0d/evilgophish#1]
Due to this decision (-> https://github.com/gophish/gophish/issues/1057) any request sent with a valid rid and a "+" appended to it will return the 'gophish contact' as well as a message stating that the email was created by a gophish server.

**Comment by fin3ss3g0d** [comment]
I wasn't aware this was a thing for GoPhish, I will pinpoint the source code responsible for it and remove it soon.

**Comment by fin3ss3g0d** [comment]
This could be an issue for the tracking tag pointing at the GoPhish server now that I think about it, will pinpoint the source code for it and remove it soon.

**Comment by fin3ss3g0d** [comment]
This could be an issue for the tracking tag pointing at the GoPhish server now that I think about it, will pinpoint the source code for it and remove it soon.

**Comment by fin3ss3g0d** [comment]
I saw this potentially being an issue with the image tracking link pointing to the GoPhish server, but you should really confirm the behavior before opening an issue. All the values in that message have already been stripped in my configurations.
![image](https://user-images.githubusercontent.com/62859381/189182476-d2e3f285-0503-4db9-8cd8-8b5fd1386288.png)
