### ISSUE TITLE
issue when using make on evilginx2 on latest version

### ISSUE THREAD

**Issue by l0stguardian** [fin3ss3g0d/evilgophish#10]
using 'make' gives error
make# github.com/mattn/go-sqlite3
sqlite3-binding.c: In function ‘sqlite3SelectNew’:
sqlite3-binding.c:128049:10: warning: function may return address of local variable [-Wreturn-local-addr]
128049 |   return pNew;
       |          ^~~~
sqlite3-binding.c:128009:10: note: declared here
128009 |   Select standin;
       |          ^~~~~~~
go build github.com/kgretzky/evilginx2: copying /tmp/go-build022226873/b001/exe/a.out: open ./bin/evilginx: permission denied
make: *** [Makefile:8: build] Error 1

**Comment by fin3ss3g0d** [comment]
`open ./bin/evilginx: permission denied` is a file permissions error. Closing as this isn't an issue directly related to the project.
