### ISSUE TITLE
Apache listening port

### ISSUE THREAD

**Issue by jvgassel** [fin3ss3g0d/evilgophish#14]
With the default installation, I have no apache service listening on port 443. I only changed the gophish admin port. Has something gone wrong during setup, or does this need manual adjustment?

root@ip-172-31-xxx.xxxx:/home/ubuntu# sudo lsof -i -P -n | grep LISTEN

sshd       632            root    3u  IPv4  23646      0t0  TCP *:22 (LISTEN)
sshd       632            root    4u  IPv6  23657      0t0  TCP *:22 (LISTEN)
apache2   2884            root    4u  IPv6  32871      0t0  TCP *:80 (LISTEN)
apache2   2886        www-data    4u  IPv6  32871      0t0  TCP *:80 (LISTEN)
apache2   2887        www-data    4u  IPv6  32871      0t0  TCP *:80 (LISTEN)
evilginx2 7486            root    9u  IPv4  37515      0t0  TCP 127.0.0.1:8443 (LISTEN)
gophish   7547            root    7u  IPv6  37987      0t0  TCP *:1337 (LISTEN)
gophish   7547            root    8u  IPv6  37989      0t0  TCP *:8080 (LISTEN)

**Comment by fin3ss3g0d** [comment]
Can you read this line of the setup script `When ready start apache with: systemctl start apache2`? It literally says it in the setup script output, you just have to read it.

**Comment by jvgassel** [comment]
Apache is running, as you could read from the output, but only on port 80

**Comment by fin3ss3g0d** [comment]
So if you look at the configuration file template in `conf/000-default.conf.template` it is only configured to listen on port 443 and there is a `sed` command issued in `setup.sh` that stops Apache from listening on port 80, so I have no idea how this could be.
