### ISSUE TITLE
evilginx2 warn: Cannot write TLS response chunked trailer from mitm'd client

### ISSUE THREAD

**Issue by jvgassel** [fin3ss3g0d/evilgophish#15]
Launched a Email campaign from gophish with the url of the evilginx2 phishlet (o365). Evilginx2 captures the username and password and after the 2FA is entered this warning shows in the log of evilginx2. 

Gophish reports only the email is sent, the rest stays empty

2022/10/16 12:21:30 [056] WARN: Cannot write TLS response chunked trailer from mitm'd client: write tcp 127.0.0.1:8443->127.0.0.1:44250: write: broken pipe

Apache, gophish and evilginx2 are running

sshd        689            root    3u  IPv4  23831      0t0  TCP *:22 (LISTEN)
sshd        689            root    4u  IPv6  23842      0t0  TCP *:22 (LISTEN)
evilginx2 30674            root    3u  IPv4  82688      0t0  TCP 127.0.0.1:80 (LISTEN)
evilginx2 30674            root    8u  IPv4  82694      0t0  TCP 127.0.0.1:8443 (LISTEN)
apache2   30704            root    4u  IPv6  82969      0t0  TCP *:443 (LISTEN)
apache2   30705        www-data    4u  IPv6  82969      0t0  TCP *:443 (LISTEN)
apache2   30706        www-data    4u  IPv6  82969      0t0  TCP *:443 (LISTEN)
gophish   30781            root    7u  IPv6  83155      0t0  TCP *:3333 (LISTEN)
gophish   30781            root    8u  IPv4  83157      0t0  TCP 127.0.0.1:8080 (LISTEN)

Any idea why the warning shows

**Comment by fin3ss3g0d** [comment]
Read the `Issues and Support` section. This issue falls into a category that I'm not supporting.
