### ISSUE TITLE
unable to start evilfeed page

### ISSUE THREAD

**Issue by fbracon** [fin3ss3g0d/evilgophish#16]
running the campaign on vps
evilginx + gophish is running correctly
started evilginx with in its folder with   ./evilginx2 -feed -g /root/evilgophish/gophish/gophish.db
started evilfeed in its folder with    ./evilfeed
this is response  Start viewing the live feed at: http://localhost:1337/
trying to start evilfeed page by   http://vpsip:1337    page not responsing

**Comment by fin3ss3g0d** [comment]
So the feed is started based on your output. You understand how `localhost` and the `127.0.0.1` IP address works right? That service is not externally exposed, you have to forward the port locally if you are not actually on that box.
