### ISSUE TITLE
the evilgophish installation always stops at installing go from source

### ISSUE THREAD

**Issue by chuksboss77** [fin3ss3g0d/evilgophish#17]
the evilgophish installation stops at the installing go from source and i even already installed go here is a screenshot of the issue
https://prnt.sc/kwfI_Z51Neyj

**Comment by fin3ss3g0d** [comment]
It looks like your system can't reach the site `go.dev`. Show the output of `ping -c 4 go.dev`.

**Comment by chuksboss77** [comment]
https://prnt.sc/ofRv3SJjk2ry

the screenshot above is where im stuck and i dont think go installed properly from the screenshot, even if it did im still having problem on the ssl certificate stage as it says no folder found

> the evilgophish installation stops at the installing go from source and i even already installed go here is a screenshot of the issue https://prnt.sc/kwfI_Z51Neyj

**Comment by fin3ss3g0d** [comment]
It is shown clearly in the error that your computer cannot reach a publicly facing website, closing.
