### ISSUE TITLE
blacklisting

### ISSUE THREAD

**Issue by TeddyBlue** [fin3ss3g0d/evilgophish#18]
i keep getting [war] blacklist: request from ip address '127.0.0.1' was blocked
blacklist in evilginx2 is set to off.
I have read the github for evilgophish reguarding apache2 and seem to be still having issues. Thanks in advance!

**Comment by fin3ss3g0d** [comment]
So the `evilginx2` blacklist is a totally different blacklist than the `Apache2` blacklist, that message appears to be coming from `evilginx2`?

**Comment by TeddyBlue** [comment]
[image: image.png]

i have not gotten go phish stood up as i am waiting on smtp server . Maybee
be issues is im accessing lure directly?
