### ISSUE TITLE
blacklisting 

### ISSUE THREAD

**Issue by darkxlord0147** [fin3ss3g0d/evilgophish#20]
"So the evilginx2 blacklist is a totally different blacklist than the Apache2 blacklist mentioned in the README, that message appears to be coming from evilginx2? This repo doesn't contain/modify the /$HOME/.evilginx/blacklist.txt file either. If this message is from evilginx2, you have made modifications to /$HOME/.evilginx/blacklist.txt, this project would never blacklist the localhost IP address as it is mandatory for the project to work properly."
127.0.0.1 is in main.go when blacklist unauth is turned on 127.0.0.1 gets blacklisted and url stops working.  and all sessions remote ip comes from 127.0.0.1 maybe removing 127.0.0.1 from main.go to "" can fix this problem. I will try that.

**Comment by fin3ss3g0d** [comment]
The entirety of this tool relies on `evilginx2` listening locally and that change would break everything. Tracking would no longer work as any victim who requests the tracking URL will be added to the blacklist. The tracking URL technically is seen as an unauthorized request. Use the project how it was intended. There is already a Apache blacklist, add your IP addresses to that.
