### ISSUE TITLE
issues when using setup.sh

### ISSUE THREAD

**Issue by l0stguardian** [fin3ss3g0d/evilgophish#22]
gives out this error
when using setup.sh or building gophish directly
go: github.com/chzyer/logex@v1.1.10: Get "https://proxy.golang.org/github.com/chzyer/logex/@v/v1.1.10.mod": dial tcp: lookup proxy.golang.org on [::1]:53: read udp [::1]:53989->[::1]:53: read: connection refused

**Comment by fin3ss3g0d** [comment]
This is an issue with your machine not being able to reach a download during build, not the script.
