### ISSUE TITLE
failed to add clicked link event to database: record not found

### ISSUE THREAD

**Issue by cchencode** [fin3ss3g0d/evilgophish#23]
<img width="1440" alt="Screen Shot 2022-11-02 at 6 24 23 PM" src="https://user-images.githubusercontent.com/108441118/199614462-53d6091f-2996-4791-b380-f7b0ab65b3cb.png">
Hi, I must commend you for the good work you are doing , modifying the existing Gophish structure with evilginx2. I have used evilgophish in the past on 2 different servers and all worked well. I decided to try a new phishlet(o365) with a server that i had used before and got results, however, after setting this up creating the lure, when I copy the link and try to access the phishing link from an incognito browser with cleared cache, I get this error on my evilginx terminal "failed to add clicked link event to database: record not found". The browser loads the phishing page just fine, but evilginx is not saving the clicked events as it usually does, where it says "tokens intercepted" et al. What could be the problem? i look forward to a favorable response.

**Comment by fin3ss3g0d** [comment]
The `RId` record is not in the database. Could be a phishing link from a previous campaign that was deleted, your browser still has cookies from a previous session, or you restarted GoPhish while evilginx2 still had an open handle to the GoPhish database. I don't have time to debug with people every time their tracking is not working and I'm not providing this kind of support. Tracking works without failure if you have setup correctly.

**Comment by cchencode** [comment]
Thanks for the swift response
