### ISSUE TITLE
SMTP issue on AWS infrastructure - Using SES & EC2

### ISSUE THREAD

**Issue by CzerkaNet** [fin3ss3g0d/evilgophish#24]
I've deployed evilgophish in AWS with incoming 443 open to 0.0.0.0/0, and all outgoing ports open to 0.0.0.0/0

The problem occurs when I try to test the sending profile - it seems to timeout from an I/O error:

time="2022-11-08T18:54:38Z" level=error msg="Max connection attempts exceeded - dial tcp xxxxxx:25: i/o timeout"

This occurs whether or not I have enabled blacklisting.  Credentials are validated by latest pulled gophish working with the SMTP setup.  Not looking for the magic bullet - but maybe more insight into how gophish interacts with SMTP in this setup?  I've interacted with Apache in every way I can think of to fix this, but I'm unable to find a solution.

**Comment by fin3ss3g0d** [comment]
There were no changes made to how GoPhish sends emails over SMTP. It's the same code as in the GoPhish repo, I just bridged tracking between them.

**Comment by CzerkaNet** [comment]
This was resolved by changing nonstandard port - from 25 to 465.  I have no idea why - just in case anyone else using SES has this issue.  fin3ss3g0d - would it be appropriate if I submitted documentation for setting up on AWS?
