### ISSUE TITLE
unable to setup

### ISSUE THREAD

**Issue by y0d4a** [fin3ss3g0d/evilgophish#29]
Hi, i bring up evilgophish but seems something i missed.
Hen i try to open url via 443 port, i am getting:
Proxy Error
The proxy server could not handle the request
Reason: Error during SSL Handshake with remote server

where i am wrong? what i miss?

thank you

**Comment by WillyNilly2020** [comment]
You need to open the traffic for that port

**Comment by fin3ss3g0d** [comment]
Apache2 needs to be restarted after setup.sh is run. Assuming this was done and you still have the issue, assuming it is an issue with your SSL certificates. A lot of missing information for what was done leading up to this point, it is difficult to help you!
