### ISSUE TITLE
Apache Restart Error

### ISSUE THREAD

**Issue by WillyNilly2020** [fin3ss3g0d/evilgophish#31]
What’s up brother, just want to quick inform you that your project is really cool and I enjoy setting this up, I’m already done setting up the certbot ssl but now Apache2 just failed me, I don’t know if it’s the SSL is the reason why it’s not working but can you inform me a little bit piece of information what I did wrong and I’ll get it fixed up?  The screen shot is below my comment thank you 👇

https://prnt.sc/pUVvKYWforiv

**Comment by fin3ss3g0d** [comment]
You can see in that error message there is a syntax error in line 9 of `/etc/apache2/sites-enabled/000-default.conf` although I'm not sure how this could have happened.

**Comment by WillyNilly2020** [comment]
That could be the reason I’ll see what I can do about it thanks

**Comment by 50shine** [comment]
![Screenshot_2022-12-23_11_27_07](https://user-images.githubusercontent.com/105277058/209367935-17bd7cd7-6276-4960-bf9c-647e6c93c392.png)
