### ISSUE TITLE
DO I RUN THIS IN SETUP.SH

### ISSUE THREAD

**Issue by 50shine** [fin3ss3g0d/evilgophish#32]
letsencrypt|certbot certonly --manual --preferred-challenges=dns --email admin@50secure.site --server https://acme-v02.api.letsencrypt.org/directory --agree-tos -d '*.50secure.site' -d '50secure.site'

and if so where do i find and up date certs

**Comment by 50shine** [comment]
![Screenshot_2022-12-23_11_27_07](https://user-images.githubusercontent.com/105277058/209367762-42027c89-978a-4bb4-815f-9e06288ce045.png)

**Comment by 50shine** [comment]
![Screenshot_2022-12-23_11_32_11](https://user-images.githubusercontent.com/105277058/209368373-e4f23fb1-308d-40ce-b04f-4c7c8f494968.png)

**Comment by fin3ss3g0d** [comment]
In case you couldn't see it, there is a pipe character in `letsencrypt|certbot` which stands for OR. You pick one depending on what is available with your package manager. But you have be able to read in order to use this project, forgot to add that to the prerequisites section.
