### ISSUE TITLE
Awesome setup !!!

### ISSUE THREAD

**Issue by WillyNilly2020** [fin3ss3g0d/evilgophish#33]
Man this project gotta be one of the most unique creative project I ever set up your the goat man I can’t find no other place to support it but I decided to support it here the picture of my setup is down below it was hard but managed to pull through can’t wait for your next up coming. Project 👨‍💻 *picture down below* 👇

https://prnt.sc/1jYuwdFHgCXg

**Comment by 50shine** [comment]
can you help me setup
