### ISSUE TITLE
need help  acme: Error ->  400 :: urn:ietf:params:acme:error:connection  refused

### ISSUE THREAD

**Issue by 50shine** [fin3ss3g0d/evilgophish#34]
equesting SSL/TLS certificates from LetsEncrypt...
[11:32:17] [!!!] acme: Error -> One or more domains had a problem:
[fls-na.amazon.secure-gateways.com] acme: error: 400 :: urn:ietf:params:acme:error:connection :: 54.161.216.210: Fetching http://fls-na.amazon.secure-gateways.com/.well-known/acme-challenge/EtNHJy1ZaHocK7ALxGWPOt1S3pXK7RGQW9gbqvie9uc: Connection refused, url:                                                                   
[images-na.amazon.secure-gateways.com] acme: error: 400 :: urn:ietf:params:acme:error:connection :: 54.161.216.210: Fetching http://images-na.amazon.secure-gateways.com/.well-known/acme-challenge/eif9C1HJtU3zAijpEFWVqxcXXXfg-Rb13gQbq9lE71c: Connection refused, url:                                                             
[www.amazon.secure-gateways.com] acme: error: 400 :: urn:ietf:params:acme:error:connection :: 54.161.216.210: Fetching http://www.amazon.secure-gateways.com/.well-known/acme-challenge/MydoMKd6wYFd8RYUqbVFhFZXesTSxTsOq67eo-O9470: Connection refused, url:                                 
![Screenshot_2023-01-01_06_32_31](https://user-images.githubusercontent.com/105277058/210169369-16c5950d-b89c-4145-9f17-c94163527449.png)

**Comment by fin3ss3g0d** [comment]
Why are you generating the certificates this way and not how it is instructed in `setup.sh`? You're not reading/following instructions properly. I'm not debugging a connection refused error for you, you will have to figure that out for yourself.

**Comment by 50shine** [comment]
i did

**Comment by 50shine** [comment]
twice

**Comment by 50shine** [comment]
so for an example if i want to run an venmo campaign in the setup.sh i would pass venmo as the root domain??
