### ISSUE TITLE
google.yaml phishlet can not get cookies.

### ISSUE THREAD

**Issue by globally0x** [fin3ss3g0d/evilgophish#4]
Great Work!

The first time, it can get username and password, no cookies, and no response after typing the password.

The second time(after an hour), google refused my connection.

server log: WARN: Cannot handshake client [www.google.com](http://www.google.com/) EOF.

**Comment by globally0x** [comment]
Great Work!

The first time, it can get username and password, no cookies, and no response after typing the password.

The second time(after an hour), google refused my connection.

server log: WARN: Cannot handshake client [www.google.com](http://www.google.com/) EOF.

**Comment by fin3ss3g0d** [comment]
Let this issue serve as a lesson for all others considering to do the same thing in the future. I state very clearly in `README.md` that if you open an issue for a phishlet, it will be closed. I provided the tool and it is up to you to create and modify phishlets. I will not be offering this kind of support.

![image](https://user-images.githubusercontent.com/62859381/190650526-b8d25ee2-2ebb-4369-bb93-68a4f9694ca5.png)

If you feel you have a phishlet that offers improvements to existing ones, or a new one altogether then submit a pull request or send them to me via email.
