### ISSUE TITLE
Evilginx returns Localhost IP 127.0.0.1 instead of Visitors IP

### ISSUE THREAD

**Issue by cchencode** [fin3ss3g0d/evilgophish#42]
I have been able to setup evilginx and also freed up port 53 so evilginx is controlling domain name resolution
## Expected Behavior

I am expecting Visitor's IP to show when my targets click the phishing url 
## Current Behavior

However, when visitors hit the phishing URL, I see the Browser, User agent and (127.0.0.1)

## Possible Solution

I need help in fixing this

## Steps to Reproduce

1.
2.
3.
4.

**Comment by fin3ss3g0d** [comment]
Right, this is intended behavior because the requests are coming from a local `Apache2` proxy and isn't really an issue. Origin IP addresses can be found in multiple places: `/var/log/apache2/access_evilginx2` and exported `GoPhish` reports.

**Comment by cchencode** [comment]
Thanks for your swift response.  I would want visitor's IP to actually come up on the terminal, when they  visit the phishing URL such as::: new visitor has arrived: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 (189.34.5.23) and NOT ::: new visitor has arrived: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 (127.0.0.1) . Because with my blacklist rules on,  certain visits to the phishing URL lead to (127.0.0.1) being blacklisted, which makes the phishing server unreachable. It would make a lot of sense if target's IP actually do come up on the terminal for me, instead of my localhost IP. Is there a way I can tweak this, so target's IP are revealed when they visit the phishing URL.  Many thanks

**Comment by fin3ss3g0d** [comment]
I could see people wanting to see the origin IP displayed in the `evilginx2` terminal. It won't take long to write, expect a commit in the next few days with this change.

**Comment by cchencode** [comment]
You have just made my night. Thanks a lot, I look forward to the revised version. Many thanks
