### ISSUE TITLE
How is it possible to disable lets encrypt request SSL to let evilnginx running port 80 with SSL

### ISSUE THREAD

**Issue by AnthraxBPLLC** [fin3ss3g0d/evilgophish#43]
## Expected Behavior
let evilnginx run on port 80, and Cloudflare take over the SSL

## Current Behavior
It keeps requesting SSL to run it and to create lures.

## Possible Solution
Maybe there's a pull request for this feature so we can get the benefit of it

## Steps to Reproduce

1. make it able to run on port 80
2. when phishlets hostname o365 domain.com, we have a choice to use lets encrypted or no if its no, let it run on port 80
3. it's for the benefit of our protecting the VPS from being suspended
4. lots of us really need this feature; if these features are unable to archive, forget about it. Maybe evilnginx needs a 
self-host SSL that runs on port 443

## Detailed Description
How is it possible to disable the let's encrypt request SSL?  let evilnginx run on port 80 without SSL
so lets Cloudflare Handle the SSL request of evilnginx

## Possible Implementation
I am willing to pay someone who can do this for me.

**Comment by fin3ss3g0d** [comment]
You want to change the code base of evilginx because the IP addresses and domains you are using have a bad reputation? Why don't you do it the right way and use a different IP space or domains? This request is absurd.
