### ISSUE TITLE
multiple domains

### ISSUE THREAD

**Issue by l0str3b3l** [fin3ss3g0d/evilgophish#59]
## Detailed Description
i am proposing a change if possible to enable evilginx to use multiple domains for a phishing campaign

**Comment by fin3ss3g0d** [comment]
This was yet another horrible design flaw from the original author, and would take most likely an extraordinary amount of time to complete. Most likely this would also require a complete re-factoring of the original code. If you would like to step up to the plate and fix it yourself, be my guest.
