### ISSUE TITLE
Evilginx3 Support?

### ISSUE THREAD

**Issue by SV-ZeroOne** [fin3ss3g0d/evilgophish#63]
First off thank you for the great work you have done on this project. Your implementation of gophish and evilginx2 is great and I love the integration you built between the two and the extra functionality.

I was just wondering if you had plans to integrate the new version (3.0.0) of evilginx3 anytime soon?

**Comment by y0k4i-1337** [comment]
That would be great!!!

**Comment by t101804** [comment]
agree

**Comment by fin3ss3g0d** [comment]
`evilginx3` update pushed!
