### ISSUE TITLE
modify subdomain after setup.sh is run

### ISSUE THREAD

**Issue by TeddyBlue** [fin3ss3g0d/evilgophish#7]
is there a way to modify subdomain after setup.sh is run? ... Is there a way to clean up and start over?

**Comment by fin3ss3g0d** [comment]
If you can read *any* `Bash`, you would notice that the files created related to subdomain values get overwritten each time you run `setup.sh` with new input. So you just opened an issue that is already solved according to your description if that is all you are concerned with. `setup.sh` assumes you know the correct values you are putting into it beforehand, and it isn't meant to be run numerous times. This isn't an issue with the code, rather you would just like this as a feature and it's not worth the commit for me as I can read simple instructions. If you would like to contribute code that provides this feature, feel free. Other than that, this is getting closed.

**Comment by TeddyBlue** [comment]
My bad, thank you!Sent from my iPhoneOn Sep 20, 2022, at 6:17 PM, Dylan Evans ***@***.***> wrote:﻿
If you can read any Bash, you would notice that the files created related to subdomain values get overwritten each time you run setup.sh with new input. So you just opened an issue that is already solved according to your description if that is all you are concerned with. setup.sh assumes you know the correct values you are putting into it beforehand, and it isn't meant to be run numerous times. This isn't an issue with the code, rather you would just like this as a feature and it's not worth the commit for me as I can read simple instructions. If you would like to contribute code that provides this feature, feel free. Other than that, this is getting closed.

**Comment by fbracon** [comment]
@TeddyBlue can you use custome subdomains on evilginx url ?

**Comment by TeddyBlue** [comment]
Yea custom sub domains by editing the yaml phishlet. Sent from my iPhoneOn Sep 23, 2022, at 6:25 PM, fbracon ***@***.***> wrote:﻿
@TeddyBlue can you use custome subdomains on evilginx url ?

**Comment by TeddyBlue** [comment]
Are you talking about modifying the lure?

**Comment by fbracon** [comment]
i talking about modifying hostname like >> phishlets hostname facebook facebook.example.com

**Comment by TeddyBlue** [comment]
Yes, no issuesSent from my iPhoneOn Sep 23, 2022, at 7:26 PM, fbracon ***@***.***> wrote:﻿
i talking about modifying hostname like >> phishlets hostname facebook facebook.example.com

**Comment by fbracon** [comment]
@TeddyBlue what is the certbot command do you use to make certificate ?
