### ISSUE TITLE
Sending Profile Email Custom Headers not working/saving. Please Update Gophish to 0.12.1

### ISSUE THREAD

**Issue by SV-ZeroOne** [fin3ss3g0d/evilgophish#74]
When trying to add a new custom email header within the email sending profile and pressing the "Add Custom Header" button, nothing happens. I do not see any API calls being made in the background.

## Expected Behavior
Expecting it to save the custom email header.

## Current Behavior
Nothing happens at all.

## Possible Solution
Apparently this was reported before within the main gophish repository and fixed within version 0.12.1. I noticed that your gophish instance is still on 0.12.0. Please could you update it?
https://github.com/gophish/gophish/issues/2639

## Steps to Reproduce
1. Open an Email Sending Profile
2. Under Email Headers add header name and value.
3. Click on "Add Custom Header"
4. Click on "Save Profile"

## Environment
Ubuntu

**Comment by SV-ZeroOne** [comment]
I was looking through the commits to figure out where the fix had been made so I could fix it myself but I honestly cant figure out where and when the fix was made for this? I've been over the latest commits a few times and nothing looks like its related to the email headers and sending profile really.

https://github.com/gophish/gophish/commits/master

**Comment by brettgus** [comment]
I've submitted a PR that will resolve this issue. #80

**Comment by harrygeorge2893** [comment]
> I've submitted a PR that will resolve this issue. #80

please how can i add an unsubscribe lisk to my email header just as shown below
![Screenshot 2023-09-11 141224](https://github.com/fin3ss3g0d/evilgophish/assets/115331787/dc7bfe83-d0be-493c-a249-ddcc9f2786bf)

**Comment by SV-ZeroOne** [comment]
Have a look at brettgus pull request.
https://github.com/fin3ss3g0d/evilgophish/pull/80/commits/2ffc6cfc86994363eea11c90fcea5b364881cec9
Simply replace the code in this file (gophish/static/js/dist/app/sending_profiles.min.js) with his code and it works.

**Comment by harrygeorge2893** [comment]
> Have a look at brettgus pull request. [2ffc6cf](https://github.com/fin3ss3g0d/evilgophish/commit/2ffc6cfc86994363eea11c90fcea5b364881cec9) Simply replace the code in this file (gophish/static/js/dist/app/sending_profiles.min.js) with his code and it works.

thank you for your help i have replaced the file and it worked but i still need help/tutorial on how to add the unsubscribe link to the email header thank you for your prompt response 
![nq](https://github.com/fin3ss3g0d/evilgophish/assets/115331787/ab7d74b9-b06e-4795-804d-822fd7d022ac)

**Comment by fin3ss3g0d** [comment]
This change has been implemented in the private sponsor's repository, sign-up if would like the feature now. Otherwise, you have to wait.
