### ISSUE TITLE
Unable to access https://127.0.0.1:3333

### ISSUE THREAD

**Issue by harrygeorge2893** [fin3ss3g0d/evilgophish#76]
After successfully installing evilgophish, i run the ./gophish but unable to access the local host

## Expected Behavior
 I expected to see the login page.

## Current Behavior
 when i try connecting to https://127.0.0.1:3333 it says 127.0.0.1 refused to connect.

## Steps to Reproduce

1.
2.
3.
4.

## Environment
 digitalocean vps ubuntu 22.04

## Severity/Priority
 very critical i have tried resolving this issues so many times but no to avail and it is blocking my work

## Screenshots

![now](https://github.com/fin3ss3g0d/evilgophish/assets/115331787/48c88080-5e51-420b-8bdc-831899d90de4)

**Comment by Drcapable03** [comment]
You might want to consider checking your configuration, especially with the Apache2.

**Comment by harrygeorge2893** [comment]
thank you for your response but can you help with apache2 configuration that works for you

**Comment by harrygeorge2893** [comment]
> thank you for your response but can you help with apache2 configuration that works for you

thank you for your response but can you help with apache2 configuration that works for you

**Comment by brettgus** [comment]
Are you accessing within the host itself?  127.0.0.1 will only work if you're trying that from the VPS.  If not you'd want to change config.json to 0.0.0.0:3333 instead so you could access it from an external IP.   However, you'd probably not want to expose that port to the open internet.  Alternatively could also do something like port forwarding through SSH.
