### ISSUE TITLE
Turnstile Validation shows "Forbidden.html" - Error loading template

### ISSUE THREAD

**Issue by LeuchterAwareness** [fin3ss3g0d/evilgophish#88]
I did the setup as described in the readme-file and started and configured evilginx and gophish. I first had some struggles to find a phishlet which also captures a session but after some time I could find one. But then another problem occourd.

When I create a lure and I use it in a GoPhish campaing, the mail is sent properly to the receivers. I then expect the turnstile captcha to validate in the backgroud or show up and to be forwarded to the phishing page.

However, after clicking on the link, there would appear the "forbidden.html" from the cloudflare template. The logs in evilginx write this: 
- [!!!] Error loading template:
- [war] session cookie not found:

According to your blog (https://fin3ss3g0d.net/index.php/2024/04/08/evilgophishs-approach-to-advanced-bot-detection-with-cloudflare-turnstile/) this could be because of a request that doesn’t trigger the lure path. But the lure path is correct as you can see in the screenshot. 

When I then click on the URL a second time it workes and the site shows up properly. Probably because of some cookies that were stored in the meantime.

I tested everything in the inkognito browser but the failure still appeared. Yesterday it worked once after I deleted all sessions and lures but now even this fix doesen't work anymore.

## Environment
I'm using an Ubuntu Server 22.04 LTS.

## Severity/Priority
Phishing does not work right now and we wanted to start a campaign (today).

## Screenshots
![image](https://github.com/fin3ss3g0d/evilgophish/assets/162611740/9fca2a0c-c86c-4485-bb5d-0ca38eaa7686)

**Comment by fin3ss3g0d** [comment]
The code works perfectly fine, there is an issue with your template as shown in the error and you need to fix it.

```go
// Define the path to your template file
	tmplPath := filepath.Join("templates", "turnstile.html")
	tmpl, err := template.ParseFiles(tmplPath)
	if err != nil {
		log.Fatal("Error loading template:", err)
		sendForbiddenResponse(writer)
		return
	}
```
