### ISSUE TITLE
Forbidden 

### ISSUE THREAD

**Issue by WesyHub** [fin3ss3g0d/evilgophish#9]
Hi, i have an issue with evilgophish, the gophish server works but when i generate a evilginx link i got a 403 Forbidden error. 

![2022-10-03 16_14_29-403 Forbidden](https://user-images.githubusercontent.com/35263085/193599937-660455f9-8e27-416a-bbb0-caaf80865856.png)

I did some research to configure apache2 to solve the problem but nothing seem to work, any advice ?

![image](https://user-images.githubusercontent.com/35263085/193600696-348ae083-5bde-46a3-8804-3bb8edebce72.png)

![image](https://user-images.githubusercontent.com/35263085/193603343-38aef273-937a-4766-9774-21fedc93893e.png)

Thanks

**Comment by fin3ss3g0d** [comment]
Your IP address is in the `/etc/apache2/blacklist.conf` file, which is originally in the `conf/` folder.

**Comment by WesyHub** [comment]
Ah it was because of the 92.0.0.0/8. Thanks !
