### ISSUE TITLE
Help with the Turnstile functionnality

### ISSUE THREAD

**Issue by benji1000** [fin3ss3g0d/evilgophish#96]
Hello,

I can't get to see the Turnstile page, even though I think I did everything that was asked in the "Cloudflare Turnstile Setup" section and the blog post. A "404 Not Found" error shows up instead of the page and I don't know what I did wrong.

## Expected Behavior

I expect to see the page I edited from the `evilginx3/templates/turnstile.html` file to show up with the Cloudflare box to tick, or be automatically redirected to my phishing page instead (if Cloudflare doesn't challenge me).

## Current Behavior

![error](https://github.com/fin3ss3g0d/evilgophish/assets/2243199/2ffa9ed3-9b4e-48bd-8488-4d0e8a414821)

If I access the phishing link in the same tab afterwards, it am redirected to my phishing page, and the credentials capture works. But my phished users would not necessarily do that, so the Turnstile feature prevents me from running my campaign.

## Steps to Reproduce

I edited the two HTML files in the `evilginx3/templates/` folder. Then I typed these commands:

```
./setup.sh <my phishing domain> "account login security" false true user_account
cd evilginx3/
./evilginx3 -feed -g ../gophish/gophish.db -turnstile 0x<1st key>:0x<2nd key> -p legacy_phishlets/
config domain <my phishing domain>
config ipv4 external <my IP>
phishlets hostname o3652 <my phishing domain>
phishlets unauth_url o3652 https://outlook.office.com/mail/
lures create o3652
lures edit 0 redirect_url https://outlook.office.com/mail/
lures get-url 0
phishlets enable o3652
blacklist unauth
phishlets unhide o3652
```

## Environment

Freshly installed Ubuntu 24.04 LTS. Only installed Apache2 and cloned the evilgophish repo, then ran the commands above.

## Logs

Here are the evilginx logs that are displayed when I access my phishing page using the link sent by Gophish:

```
[15:22:45] [war] session cookie not found: https://<my phishing domain>/QIsKVFdu?user_account=YjmQjK98e2thBBu9vUyorQYshxEZzzQ-557kZuOU4uRhrB-2tjxJQCgl33T1-rM_xNJ1H_dWGTZMEfPQ1kA8nORX1i4z (<My IP>) [o3652]
[15:22:45] [imp] [2] [o3652] new visitor has arrived: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.0 (<My IP>)
[15:22:45] [inf] [2] [o3652] landing URL: https://<my phishing domain>/QIsKVFdu?user_account=YjmQjK98e2thBBu9vUyorQYshxEZzzQ-557kZuOU4uRhrB-2tjxJQCgl33T1-rM_xNJ1H_dWGTZMEfPQ1kA8nORX1i4z
: Error sending websocket message: dial tcp 127.0.0.1:1337: connect: connection refused
```

I guess the last line is connected to my issue, but I don't know what to do with that.

## Possible Solution

When I browse my Apache logs, I can see the 404 request to the `/validate-captcha` page and it comes from 127.0.0.1, so I guess that's evilginx that tries to access the page using a websocket? But why doesn't it work? Did I miss something with the Apache setup?

Thank you for your help!

**Comment by wretiii** [comment]
When testing, use the URL from GoPhish rather than Evilginx.

**Comment by benji1000** [comment]
I use the URL that Gophish generates for each user individually and that is sent to them by email), and not the one that evilginx generates for me to input into Gophish (`https://<my phishing domain>/<8 characters>`). Am I using the correct one?

**Comment by fin3ss3g0d** [comment]
It's written all over the `README.md` file, but I'm not offering support for this free version of the repository. If you want support in the future, become a sponsor. The issue is shown directly in your screenshot here:

![image](https://github.com/fin3ss3g0d/evilgophish/assets/62859381/6eb9fd20-4483-4df8-acce-8272f2c46350)

Your Apache server is listening on port 80 when the local Turnstile server should be listening on port 80. Hence the 404 response. My advice would be to read the error message next time, they are typically displayed for a reason.
